### ISSUE TITLE
FeatureTileSource is not loading from geopackage

### ISSUE THREAD

**Issue by muruganandham** [mousebird/WGMaply-GeoPackage#10]
I'm trying to load a feature table from a geopackage, it is not loading as expected. I can see only a blank screen. But, i can see the list of tables in layer menu option. Please see the attached image. The geopackage is downloaded from 
 [ArcGIS server](https://www.arcgis.com/home/item.html?id=68ec42517cdd439e81b036210483e8e7). But, `GPKGTileSource` is working well.

![simulator screen shot - ipad pro 9_7 - 2018-10-22 at 13 08 38](https://user-images.githubusercontent.com/4518393/47282275-360b8680-d5fc-11e8-94c8-bb4ddab5bdd8.png)

**Comment by mousebird** [comment]
GeoPackages are tricky.  There are a million different ways to store the same data and we don't always pick up on them.

I should remember who you're working for, but I've forgotten which of the GeoPackage users it might be.  If you're on support, email me directly and we'll sort it out.

**Comment by robert-claypool** [comment]
@muruganandham, Please submit a [minimal, complete, and verifiable example](https://stackoverflow.com/help/mcve). The screenshot and link to data is helpful, but not enough to resolve whatever is the issue.

**Comment by mousebird** [comment]
I just updated the WGMaplyGPkgTest app in the GeoPackage repo to the latest WG-Maply.
I'm happy to say it wasn't too hard.

But rivers.gpkg is working for me there.  I see both the river vectors and the river tiles.

**Comment by muruganandham** [comment]
Thanks @mousebird, now I can see the expected result.
